# Default variables for developers running cargo run and cargo test.
[env]
RUST_BACKTRACE = "1"
RUST_LOG = "cipherly=trace,tower_http=trace,axum=trace,info"
KEKS='{"v1":"jRg36ErQ6FLcc7nZgngOpjJnJLGwA3xaMy0yx1pxJrI"}'
ENABLE_TEST_CREDS = "true"

[build]
rustflags = [
  "-C",
  "force-unwind-tables",
] # Needed for backtraces: https://github.com/rust-lang/rust/issues/94815
